dj/models/user.py
# import peewee as pw
from django.db import models
from werkzeug.security import generate_password_hash
from flask_login import UserMixin
from .base_model import BaseModel
import os
from django.core.exceptions import ObjectDoesNotExist
from playhouse.hybrid import hybrid_property
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class UserValidation():
    @classmethod
    def validate_length(klass, value):
        if len(value) < 5:
            raise ValidationError(
                _('%(value)s is too short'),
                params={'value': value},
            )


class User(UserMixin, BaseModel):
    username = models.CharField(
        max_length=100, unique=False, validators=[UserValidation.validate_length])
    password = models.CharField(max_length=100)
    email = models.CharField(max_length=100, unique=True)
    role = models.CharField(max_length=100, default="user")
    profile_picture = models.TextField(max_length=200, null=True)

    @classmethod
    def get_or_none(self, **kwargs):
        try:
            return User.objects.get(**kwargs)
        except ObjectDoesNotExist:
            return None

    def validate(self):
        duplicate_username = User.get_or_none(username=self.username)
        duplicate_email = User.get_or_none(email=self.email)

        if duplicate_username and duplicate_username.id != self.id:
            self.errors.append('Username not unique')
        if duplicate_email and duplicate_email.id != self.id:
            self.errors.append('Email not unique')
        if len(self.password) < 8 or len(self.password) > 25:
            self.errors.append('Password must between 8-25 characters.')
        else:
            self.password = generate_password_hash(self.password)

    @hybrid_property
    def profile_image_url(self):
        return os.environ['S3_DOMAIN'] + self.profile_picture

instagram_api/blueprints/users/views.py
from flask import Blueprint

users_api_blueprint = Blueprint('users_api',
                             __name__,
                             template_folder='templates')

@users_api_blueprint.route('/', methods=['GET'])
def index():
    return "USERS API"

instagram_web/blueprints/users/views.py
import peewee as pw
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required,current_user,login_user
from dj.models.user import User
from instagram_web.util.helpers import upload_file_to_s3
from werkzeug.utils import secure_filename

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
    valid_email = request.args.get('v_e')

    return render_template('users/new.html', valid_email=valid_email)


@users_blueprint.route('/', methods=['POST'])
def create():
    email = request.form.get('email')
    username = request.form.get('username')
    password = request.form.get('password')

    new_user = User(
        email=email,
        username=username,
        password=password)

    v_e = False

    try:
        if new_user.save():
            login_user(new_user)
            flash('Successfully created a user!', "success")
            v_e = True

        else:
            flash("An error occurred!", "danger")

    except pw.IntegrityError as e:
        print(e)

    return redirect(url_for("users.new", v_e=v_e))


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    user = User.objects.get(username=username)
    return render_template("users/show.html",user=user)


@users_blueprint.route('/', methods=["GET"])
def index():
    return "USERS"


@users_blueprint.route('/<id>/edit', methods=['GET'])
@login_required
def edit(id):
    user = User.objects.get(id=id)
    if (current_user.role == "admin" or current_user.id==user.id):
        return render_template("users/edit.html",user=user)
    else:
        flash(f"You are not allowed to update {user.username}'s profile",'danger')
        return render_template("users/show.html",user=current_user)


@users_blueprint.route('/<id>', methods=['POST'])
@login_required
def update(id):
    user = User.objects.get(id=id)
    if current_user == user :
        user.username = request.form.get('username')
        user.email = request.form.get('email')
        user.password = request.form.get('password')
        if user.save():
            flash("Successfully updated.","success")
            return redirect(url_for('users.edit',id=id))
        else:
            errors = user.errors
            for error in errors:
                flash(error,"danger")
            flash("Can not update profile.","danger")
            return render_template("users/edit.html",user=user)
    else:
        flash(f"You are not allowed to update {user.username}'s profile",'danger')
        return render_template("users/edit.html",user=user)

@users_blueprint.route('/<id>/picture', methods=['POST'])
@login_required
def update_picture(id):
    # get file from request
    file = request.files.get("user_file")
    # if no file in request
    if not file:
        flash("Please choose a file.","danger")
        return render_template('images/new.html')
    # if file in request
    file.filename = secure_filename(file.filename)
    output = upload_file_to_s3(file)
    # if no image link get from upload function mean upload is unsuccessful
    if not output:
        flash("Unable to upload file, try again.","danger")
        return render_template('images/new.html')
    # if img link return, mean upload successful
    else:
        # get current user
        user = User.update(profile_picture = output).where(User.id == current_user.id)
        # save profile image link in user class
        user.execute()
        flash("Profile picture updated","success")
        return redirect(url_for('users.show', username=current_user.username))

instagram_web/blueprints/users/templates/users/edit.html
{% extends "_layout.html" %}
{% block title %}
  Edit
{% endblock %}
{% block content %}
<div class="w-100 d-flex flex-column align-items-center my-3">
    <h1>Upload Your Profile Picture</h1>
    <form action="{{url_for('users.update_picture',id=user.id)}}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" / >
        <br>
        <input type="file" name="user_file">
        <br>
        <button class="btn btn-primary" type="submit">Upload</button>
    </form>
</div>


<div class="w-100 d-flex flex-column align-items-center my-3">
    <h1>Update {{user.username}}'s Profile</h1>
    <form action="{{url_for('users.update',id=user.id)}}" method="POST"> 
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" / >
        <div class="form-group">
            <label for="name">Username:</label>
            <input type='text' required name='username' value="{{user.username}}" class="form-control" / >
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type='email' name='email' value="{{user.email}}" class="form-control" / >
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type='password' required name='password' class="form-control" / >
            <small>Fill your password to confirm the chages.</small>
        </div>
        <button type="submit" class="btn btn-outline-primary mt-2">Update</button>
    </form>
</div>


{% endblock %}

instagram_web/blueprints/users/templates/users/new.html
{% extends "_layout.html" %} {% block content %}
<div class="w-100 d-flex flex-column align-items-center my-3">
  <h1 class="my-3">Sign up here!</h1>

  <form
    action="{{ url_for('users.create') }}"
    method="POST"
    class="needs-validation"
    id="sign-up-form"
  >
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="form-group">
      <label for="email">Email address</label>
      <input
        type="email"
        class="form-control"
        {# class="form-control {% if valid_email %} is-valid {% elif valid_email == 'False' %} is-invalid {% endif %}" #}
        id="email"
        name="email"
        aria-describedby="emailHelp"
        placeholder="Enter email"
      />

      <small id="emailHelp" class="form-text text-muted"
        >We'll never share your email with anyone else.</small
      >

      {% if valid_email == 'True' %}
      <div class="valid-feedback">
        Looks good!
      </div>

      {% elif valid_email == 'False' %}
      <div class="invalid-feedback">
        Looks bad!
      </div>
      {% endif %}
    </div>
    <div class="form-group">
      <label for="username">Username</label>
      <input
        type="text"
        class="form-control"
        id="username"
        name="username"
        aria-describedby="emailHelp"
        placeholder="Enter username"
      />
    </div>

    <div class="form-group has-feedback">
      <label for="password">Password</label>
      <input
        type="password"
        name="password"
        class="form-control"
        id="password"
        placeholder="Password"
        minlength="8"
        required
      />
      <div class="invalid-feedback">
        Please choose a longer password.
      </div>
    </div>
    <div class="valid-feedback">
      Looks good!.
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

<script>
    function validatePassword(e) {
      if (e.target.value.length >= 8) {
        alert("YAY");
      }
      return e.target.value.length >= 8;
    }

    console.log(document.getElementById("password"));

    document.getElementById("password").addEventListener("input", e => {
      validatePassword(e);
    });

  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>

{% endblock %}

instagram_web/blueprints/users/templates/users/new.html.j2
{% extends "_layout.html" %} {% block content %}

<div class="w-100 d-flex flex-column align-items-center my-3">
  <h1 class="my-3">Sign up here!</h1>
  <form action="{{ url_for('users.create') }}" method="POST">
    <div class="form-group">
      <label for="email">Email address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        aria-describedby="emailHelp"
        placeholder="Enter email"
      />
      <small id="emailHelp" class="form-text text-muted"
        >We'll never share your email with anyone else.</small
      >
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        name="password"
        class="form-control"
        id="password"
        placeholder="Password"
      />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

instagram_web/blueprints/users/templates/users/show.html
{% extends "_layout.html" %}
{% block title %}
  Profile
{% endblock %}
{% block content %}
<div class="w-100 d-flex flex-column align-items-center my-3">
    <h1>{{user.username}}'s Profile</h1>
    <img src="{{user.profile_image_url}}" alt="profile-image" width="300">
</div>
{% endblock %}